feat: added actions, reducers using redux and first try to use it
KoTuK2306/productsList pull request #2
Opened 2022-04-26 17:30 UTC by KoTuK2306

2022-04-27 07:14 UTC, pavelsokolov21 requested changes

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/hooks/useTypedSelector.ts
> +export const useTypedDispatch = (): AppDispatch => useDispatch();
это же отдельный хук => отдельный файл для хука

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/App.tsx
> +  const showLoadOrError = () => {
эта функция не нужна. Данная функция нарушает принцип единственной ответственности. Если хочешь вынесть в функции, то создай отдельную под спиннер и отдельную под ошибку.
Или же прям в JSX напиши

```tsx
{loading && <Spinner />}
{error && <Error />}
```

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/App.tsx
> +  const { error, loading, products } = useTypedSelector((state) => state.products);
название `loading` не совсем олицетворяет бул-тип. Для любых булевых переменных используются преффиксы `is, has, etc.`. То есть, тут лучше использовать `isLoaded` (не `isLoading`, это не самое крутое название :) )

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/App.tsx
> +        <div key={product.tracking_id} className={classes.object}>
это компонент карточки или что-то из этого. Также под него надо бы сделать отдельный контейнер/секцию

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/hooks/useTypedSelector.ts
> +import { RootState } from "../store/reducers";
остальные импорты ниже бибок

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/components/Spinner/Spinner.tsx
> +        <div className={`${classes.spinner} ${classes.spinnerInner}`} />
я бы рекомендовал использовать библиотеку `classnames` вместо использования шаблонной строки

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/store/actionCreators/product.ts
> +    } catch (e) {
если тебе не нужен объект ошибки, то ты его можешь  не писать 

```ts
} catch {...}
```

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/store/index.ts
> +import thunk from "redux-thunk";
сначала бибки

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/types/products.ts
> +  products: any[];
по лицу за `any`. Его нужно использовать максимально редко и в самых крайних случаях

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/store/actionCreators/product.ts
> +      dispatch({ type: ProductActionTypes.FETCH_PRODUCTS });
этот объект тоже оборачивается в функцию типа `actionCreator`

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/types/products.ts
> +export type ProductAction = FetchProductAction | FetchProducSuccesstAction | FetchProductErrorAction;
```suggestion
export type ProductAction = FetchProductAction | FetchProductSuccessAction | FetchProductErrorAction;

```

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/store/actionCreators/product.ts
> +          dispatch({ type: ProductActionTypes.FETCH_PRODUCTS_SUCCESS, payload: data });
отдельный экшн

2022-04-27 07:14 UTC, pavelsokolov21 commented on src/store/actionCreators/product.ts
> +      dispatch({
отдельный экшн

2022-04-27 07:16 UTC, KoTuK2306 commented on src/App.tsx
> +        <div key={product.tracking_id} className={classes.object}>
Это будет сделано в будущем, не в этом PR. Как раз после закрытия этого PR я буду верстать карточку под продукт

2022-04-28 11:06 UTC, pavelsokolov21 requested changes

2022-04-28 11:06 UTC, pavelsokolov21 commented on src/App.tsx
> +      {isLoaded && <Spinner />}
то есть, если загрусился, то спиннер?

2022-04-28 11:06 UTC, pavelsokolov21 commented on src/store/actionCreators/product.ts
> +export const fetchProducts = () => {
Это такой же экшн, только асинхронный. Нет смысла его в отдельную папку выносить. Лучше ему быть там же, где и остальные экшены продукта

2022-04-28 11:12 UTC, KoTuK2306 commented on src/App.tsx
> +      {isLoaded && <Spinner />}
Пока загружается спиннер. Ты попросил назвать isLoaded, но тут, мне кажется, isLoading (загружается или нет)

2022-04-28 16:08 UTC, pavelsokolov21 approved these changes

2022-04-28 16:25 UTC, merged