feat: added clear search button
KoTuK2306/productsList pull request #9
Opened 2022-05-03 17:32 UTC by KoTuK2306

2022-05-03 19:50 UTC, pavelsokolov21 requested changes

2022-05-03 19:50 UTC, pavelsokolov21 commented on src/tsxIcons/triangle.tsx
> +const icon = {
```suggestion
const icons = {
```

2022-05-03 19:50 UTC, pavelsokolov21 commented on src/tsxIcons/triangle.tsx
> +export const triangle = icon.triangle;
чтобы зачем?

2022-05-03 20:58 UTC, KoTuK2306 commented on src/tsxIcons/triangle.tsx
> +export const triangle = icon.triangle;
чтобы ты спросил долбоебина

2022-05-04 06:35 UTC, pavelsokolov21 approved these changes

2022-05-04 06:36 UTC, merged